name: ClockSystem-TP3 - Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: "8.10"

      - name: Build with Gradle 8.10
        run: gradle build --no-daemon -Djava.awt.headless=true

      - name: Publish a test report
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: test/reports/artifact/
