name: ClockSystem-TP3 - PMD Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"

      - name: Run PMD analysis
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: "java-basic"

      - name: Upload PMD report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: pmd-report.xml
