name: ClockSystem-TP3 - PMD Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run PMD analysis
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          version: "6.55.0"
          sourcePath: "app/src/main/java"
          rulesets: "java-basic"

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
