name: ClockSystem-TP3 - PMD Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run PMD analysis
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: "ruleset.xml"

      - name: Upload PMD report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: app/build/reports/analysis
